CREATE TABLE IF NOT EXISTS exercicio2.product(
id INTEGER GENERATED ALWAYS AS IDENTITY;
barcode VARCHAR(200) UNIQUE NOT NULL, 
name VARCHAR(50) TEXT NOT NULL, 
description VARCHAR(10000) TEXT NOT NULL,
quantity INTEGER TEXT NOT NULL,
price NUMERIC(10,2) NOT NULL );