flyway.url=jdbc:postgresql://ep-noisy-flower-acmfbiwh-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require
flyway.user=neondb_owner
flyway.password=npg_4nsGP9EpZfkS
flyway.locations=filesystem:./migrations