ALTER TABLE exercicio8.owners ENABLE ROW LEVEL SECURITY;

ALTER TABLE exercicio8.houses ENABLE ROW LEVEL SECURITY;

ALTER TABLE exercicio8.house_owner ENABLE ROW LEVEL SECURITY;

ALTER TABLE exercicio8.sellers ENABLE ROW LEVEL SECURITY;

ALTER TABLE exercicio8.sales ENABLE ROW LEVEL SECURITY;

ALTER TABLE exercicio8.furniture ENABLE ROW LEVEL SECURITY;

ALTER TABLE exercicio8.rooms ENABLE ROW LEVEL SECURITY;