REVOKE ALL PRIVILEGES
ON SCHEMA exercicio8
FROM owners;

REVOKE ALL PRIVILEGES
ON ALL TABLES IN SCHEMA exercicio8
FROM owners;

REVOKE ALL PRIVILEGES
ON SCHEMA exercicio8
FROM sellers;

REVOKE ALL PRIVILEGES
ON ALL TABLES IN SCHEMA exercicio8
FROM sellers;

DROP ROLE owners;
DROP ROLE sellers;