REVOKE ALL PRIVILEGES
ON SCHEMA exercicio8
FROM dba;

REVOKE ALL PRIVILEGES
ON ALL TABLES IN SCHEMA exercicio8
FROM dba;

REVOKE ALL PRIVILEGES
ON ALL FUNCTIONS IN SCHEMA exercicio8
FROM dba;

REVOKE dba FROM anna;
REVOKE dba FROM gustavo;

